- src/stream-chat-net-test/ChannelTests.cs
- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net-test/UserTests.cs
- src/stream-chat-net/Channel.cs
- src/stream-chat-net/IChannel.cs
- src/stream-chat-net/IUsers.cs
- src/stream-chat-net/Users.cs
`ReactivateUser` endpoint
Fix broken tests and `Ban` command
> fix loads of broken tests and add reactivate endpoint

- src/stream-chat-net/ChannelObject.cs
> [CHAT-825] adjust returned channel.config.commands type to include the commands info

- src/stream-chat-net/Event.cs
> [CHAT-826] make json helpers public for event type

- src/stream-chat-net-test/UserTests.cs
- src/stream-chat-net/User.cs
- src/stream-chat-net/Users.cs
> Add partial update

- src/stream-chat-net/Client.cs
> Make JWTToken public

- src/stream-chat-net-test/stream-chat-net-test.csproj
- src/stream-chat-net/stream-chat-net.csproj
> Add support for .Net 4.7.2

- src/stream-chat-net/Client.cs
- src/stream-chat-net/ClientOptions.cs
- support regions with URLs according to [docs](https://getstream.io/chat/docs/multi_region/?language=c_sharp)
- tests skipped, changes have little impact
> update of api locations according to documentation

- src/stream-chat-net/Channel.cs
- src/stream-chat-net/IChannel.cs
> Adding system message support for addMembers and removeMembers

- src/stream-chat-net-test/ChannelTests.cs
- src/stream-chat-net/Channel.cs
> Fix system message marshaling

- README.md
- src/stream-chat-net-test/ChannelTests.cs
> Add some tests/notes for multi-tenant

- README.md
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IClient.cs
> Allow to hard delete message by message id

- src/stream-chat-net/Client.cs
> Fix hard delete of a message

- src/stream-chat-net/Client.cs
> Add version header

- README.md
> Fix readme for export user

- README.md
- src/stream-chat-net/IUsers.cs
- src/stream-chat-net/Users.cs
> Add missing GDPR options

- src/stream-chat-net/Message.cs
> Add mml into message

- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IClient.cs
- src/stream-chat-net/RateLimits.cs
This PR introduces support for the GetRateLimits endpoint to retrieve rate limits quotas and usage.
> support GetRateLimits

- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Message.cs
- src/stream-chat-net/MessageInput.cs
> Add silent message support

- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Channel.cs
- src/stream-chat-net/IChannel.cs
> Add channel show/hide

- src/stream-chat-net/Exception.cs
- [ x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x ] The code changes follow best practices
- [ n/a ] Code changes are tested (add some information if not applicable)
This exposes the error codes returned by the API, when available on the exception state. Previously, these error codes were parsed from the payload but not used.
> expose error codes from rest response

- README.md
- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IClient.cs
- src/stream-chat-net/Message.cs
- src/stream-chat-net/QueryOptions.cs
> Feature: Message search

- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/ExportChannel.cs
- src/stream-chat-net/IClient.cs
> Export channels endpoint

- README.md
> Update example for setting channel extra data

- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IClient.cs
- src/stream-chat-net/Message.cs
> Add GetMessage endpoint.  Deserialise CID in Message.

- src/stream-chat-net/APPSettingsWithDetails.cs
- src/stream-chat-net/AppSettings.cs
> support AsyncURLEnrichEnabled flag

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- src/stream-chat-net-test/ClientTests.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IClient.cs
- src/stream-chat-net/Message.cs
Partial Message Update feature, plus tests.
> feat: add partial message update

- .gitignore
- README.md
- commitlint.config.js
- src/stream-chat-net-test/ChannelTests.cs
- src/stream-chat-net-test/PermissionTests.cs
- src/stream-chat-net-test/Utils.cs
- src/stream-chat-net/ApiResponse.cs
- src/stream-chat-net/Channel.Members.cs
- src/stream-chat-net/ChannelType.cs
- src/stream-chat-net/Client.cs
- src/stream-chat-net/IChannel.cs
- src/stream-chat-net/IClient.cs
- src/stream-chat-net/IPermissions.cs
- src/stream-chat-net/JSONHelpers.cs
- src/stream-chat-net/Permision.cs
- src/stream-chat-net/PermissionClient.cs
- src/stream-chat-net/PermissionV2.cs
- src/stream-chat-net/Rest/RestRequest.cs
- src/stream-chat-net/ServiceBase.cs
- src/stream-chat-net/User.cs
- src/stream-chat-net/Users.cs
> feat: add permissions v2

- .github/workflows/reviewdog.yml
- src/stream-chat-net-test/ChannelTests.cs
- src/stream-chat-net/Channel.Members.cs
- src/stream-chat-net/Channel.Messaging.cs
- src/stream-chat-net/IChannel.cs
- src/stream-chat-net/User.cs
- Add hide history to add members
- Add reviewdog
> feat: add hidehistory to add members

- src/Clients/ChannelClient.Members.cs
- src/Clients/IChannelClient.cs
- src/Clients/IMessageClient.cs
- src/Clients/MessageClient.cs
- tests/ChannelClientTests.cs
- tests/MessageClientTests.cs
add helper methods for user invitation, acceptance and rejection
> feat: add helper methods for user invitation, acceptance and rejection

- src/Clients/EventClient.cs
- src/Clients/IEventClient.cs
- src/Models/Event.cs
- tests/EventClientTests.cs
> feat: add user custom events

- src/Clients/FlagClient.cs
- src/Clients/IFlagClient.cs
- src/Models/Moderation.cs
- tests/FlagClientTests.cs
> feat: add new moderation apis

- src/Models/ChannelConfig.cs
> feat: add command override

- src/Models/AppSettings.cs
- src/Models/ChannelType.cs
> feat: add reminders

- src/Clients/IChannelClient.cs
- src/Models/Channel.cs
- tests/ChannelClientTests.cs
> feat(truncate): add user id for truncation

- .github/workflows/ci.yaml
- .gitignore
- src/Clients/IMessageClient.cs
- src/Models/AppSettingsWithDetails.cs
- tests/stream-chat-net-test.csproj
> ci: print test coverage result

- .github/workflows/ci.yaml
- .github/workflows/initiate_release.yml
- .github/workflows/release.yaml
- .github/workflows/reviewdog.yml
- src/Models/AppSettings.cs
- src/Models/AppSettingsWithDetails.cs
> feat: add apn template field

- README.md
- tests/FlagClientTests.cs
* update offline only config for push
* use specific channel for each test
> chore: fix scheduled tests

- src/Models/MessageRequest.cs
- src/Utils/JsonSerializerSettings.cs
- src/Utils/Utils.cs
- tests/MessageClientTests.cs
> [PBE-537] Possibility to send system messages

- src/Clients/IMessageClient.cs
- src/Clients/MessageClient.cs
- src/Models/Channel.cs
- src/Models/ChannelType.cs
- src/Models/Message.cs
- src/Models/MessageRequest.cs
- tests/MessageClientTests.cs
> [PBE-868] feat: added support for pending messages

- tests/BlocklistClientTests.cs
- tests/ChannelTypeClientTests.cs
- tests/CommandClientTests.cs
- tests/TestBase.cs
Change flaky tests to make a few attempts (with delay) on operations that might fail due to data propagation delay (sometimes there's few ms delay between writing the data and being able to read it)
> Improve tests resilience

- src/Models/ChannelMember.cs
- tests/ChannelClientTests.cs
Add `ChannelMember.NotificationsMuted` property
https://stream-io.atlassian.net/browse/PBE-2549
> Add ChannelMember.NotificationsMuted property

- samples/DocsExamples/ChannelUpdate.cs
> Add code examples for archiving and pinning channels

- src/Models/Message.cs
- src/Models/MessageRequest.cs
- tests/MessageClientTests.cs
> feat: added restricted visibility feature

- src/Clients/IMessageClient.cs
- src/Clients/MessageClient.cs
- src/Models/Message.cs
- src/Models/MessageRequest.cs
> [MOD-506] add force_moderation param support

- CHANGELOG.md
- src/stream-chat-net.csproj
> chore(release): 2.16.0

- src/Models/Channel.cs
- src/Models/ChannelConfig.cs
- tests/MessageCountTests.cs
> feat (cha-1154): add channel message count

- src/Models/Message.cs
- tests/MemberMessageResponseTests.cs
> [CHA-1211] Added Member to message response
